#!/bin/bash
set -e
source /mnt/user/data/scripts/rythmx/venv/bin/activate
cd /mnt/user/data/scripts/rythmx/app
export RYTHMX_ENV_FILE="/mnt/user/data/scripts/rythmx/credentials.env"
python -m runners.new_releases
deactivate
