"""
artwork.py - Local artwork serving route.

Serves content-addressed thumbnails generated by app.services.artwork_store.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import Response

from app.services.artwork_store import get_thumb

router = APIRouter()


@router.get("/artwork/{content_hash}")
def get_artwork(
    content_hash: str,
    s: int = Query(default=300, ge=32, le=2048),
):
    """
    Serve cached/resized local artwork thumbnail as WebP.

    Cache policy is immutable because content is addressed by SHA-256 hash.
    """
    try:
        payload = get_thumb(content_hash, size=s)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail={"status": "error", "message": "Artwork not found"})
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail={"status": "error", "message": str(exc)})
    except ValueError as exc:
        raise HTTPException(status_code=400, detail={"status": "error", "message": str(exc)})

    return Response(
        content=payload,
        media_type="image/webp",
        headers={"Cache-Control": "public, max-age=31536000, immutable"},
    )
